version: '4.7'
services:
  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    restart: always
    ports:
      - 80:80
    volumes:
      - ./geducar:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - mysql
    networks:
      - laravel
  
  mysql:
    image: mysql:5.7
    container_name: mysql
    restart: always
    environment:
      MYSQL_DATABASE: geducar
      MYSQL_USER: laravel
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: admin.root
    ports:
      - 33069:3306
    volumes:
      - ./my-sql:/var/lib/mysql
    networks:
      - laravel
  php:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: php
    volumes:
      - ./geducar:/var/www/html
    ports:
      - 9000:80
    networks:
      - laravel

networks:
  laravel: